# Generated by Django 6.1.1 on 2026-09-03 16:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='documentos.empresa')),
            ],
            options={
                'ordering': ['empresa__nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='MapeoRubroCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo_rubro', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('P', 'Padre'), ('V', 'Valorable')], max_length=1)),
                ('cuenta_contable', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeos_rubro', to='documentos.proyecto')),
            ],
            options={
                'ordering': ['proyecto', 'codigo_rubro'],
            },
        ),
        migrations.CreateModel(
            name='MapeoCategoriaCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(max_length=150)),
                ('cuenta_general_original', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeos_categoria', to='documentos.proyecto')),
            ],
            options={
                'ordering': ['proyecto', 'categoria'],
            },
        ),
        migrations.CreateModel(
            name='MapeoProductoIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('porcentaje_iva', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('categoria', models.CharField(blank=True, help_text='Relacion local producto-categoria; no proviene del maestro de IVA.', max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeos_producto_iva', to='documentos.empresa')),
            ],
            options={
                'ordering': ['empresa', 'codigo_producto'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo_producto'), name='uq_producto_empresa_codigo'), models.CheckConstraint(condition=models.Q(('porcentaje_iva__gte', 0), ('porcentaje_iva__lte', 100)), name='ck_producto_iva_0_100')],
            },
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_proyecto_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='mapeorubrocuenta',
            constraint=models.UniqueConstraint(fields=('proyecto', 'codigo_rubro'), name='uq_rubro_proyecto_codigo'),
        ),
        migrations.AddConstraint(
            model_name='mapeorubrocuenta',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['P', 'V'])), name='ck_rubro_tipo_p_o_v'),
        ),
        migrations.AddConstraint(
            model_name='mapeocategoriacuenta',
            constraint=models.UniqueConstraint(fields=('proyecto', 'categoria'), name='uq_categoria_proyecto_nombre'),
        ),
    ]
