# Generated by Django 6.1.1 on 2026-09-03 16:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('PROCESANDO', 'Procesando'), ('VALIDADO', 'Validado'), ('CON_ERRORES', 'Con errores'), ('EXPORTADO', 'Exportado')], default='CREADO', max_length=20)),
                ('cantidad_archivos', models.PositiveIntegerField(default=0)),
                ('cantidad_validos', models.PositiveIntegerField(default=0)),
                ('cantidad_con_errores', models.PositiveIntegerField(default=0)),
                ('total_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='documentos.proyecto')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo_original', models.CharField(max_length=255)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('empresa_detectada', models.CharField(blank=True, max_length=255)),
                ('proyecto_detectado', models.CharField(blank=True, max_length=100)),
                ('proveedor', models.CharField(blank=True, max_length=255)),
                ('ruc_proveedor', models.CharField(blank=True, max_length=30)),
                ('numero_interno_erp', models.CharField(blank=True, max_length=100)),
                ('numero_factura_proveedor', models.CharField(blank=True, max_length=100)),
                ('numero_factura_normalizado', models.CharField(blank=True, max_length=100)),
                ('clave_proveedor', models.CharField(blank=True, max_length=400)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDO', 'Valido'), ('ADVERTENCIA', 'Advertencia'), ('ERROR', 'Error'), ('DUPLICADO', 'Duplicado'), ('EXPORTADO', 'Exportado')], default='PENDIENTE', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('mensajes', models.JSONField(blank=True, default=list)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentos.lotecarga')),
            ],
            options={
                'ordering': ['lote', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LineaReclasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('cuenta', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo_movimiento', models.CharField(choices=[('1', 'Debito'), ('2', 'Credito')], max_length=1)),
                ('detalle', models.CharField(max_length=500)),
                ('codigo_rubro', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=150)),
                ('cuenta_general_origen', models.CharField(blank=True, max_length=100)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='documentos.documentolote')),
            ],
            options={
                'ordering': ['documento', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('documento', 'orden'), name='uq_linea_documento_orden'), models.CheckConstraint(condition=models.Q(('tipo_movimiento__in', ['1', '2'])), name='ck_linea_tipo_1_o_2')],
            },
        ),
        migrations.AddIndex(
            model_name='documentolote',
            index=models.Index(fields=['lote', 'hash_sha256'], name='idx_documento_lote_hash'),
        ),
        migrations.AddIndex(
            model_name='documentolote',
            index=models.Index(fields=['clave_proveedor', 'estado'], name='idx_documento_clave_estado'),
        ),
    ]
