# Generated by Django 6.1.1 on 2026-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_lotecarga_documentolote_lineareclasificacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapeocategoriacuenta',
            options={'ordering': ['proyecto', 'categoria', 'cuenta_general_original']},
        ),
        migrations.RemoveConstraint(
            model_name='mapeocategoriacuenta',
            name='uq_categoria_proyecto_nombre',
        ),
        migrations.AddConstraint(
            model_name='mapeocategoriacuenta',
            constraint=models.UniqueConstraint(fields=('proyecto', 'categoria', 'cuenta_general_original'), name='uq_categoria_proyecto_cuenta'),
        ),
    ]
