# Generated by Django 6.1.1 on 2026-09-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_producto_iva_por_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_organizacion', models.CharField(default='Meneses Constructores', max_length=255)),
                ('subtitulo', models.CharField(default='Automatización y control contable', max_length=255)),
                ('logotipo', models.ImageField(blank=True, upload_to='institucion/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
