# Generated by Django 6.1.1 on 2026-09-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_configuracion_institucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigo_consulta_documentos',
            field=models.CharField(blank=True, help_text='Identificador mostrado por Consulta de Documentos; no cambia el código presupuestario.', max_length=150),
        ),
    ]
